CFLAGS=-Wall -ansi -pedantic -g -lm

all: pennies greedy chart credit

pennies: pennies.c
	cc -o $@ $^ $(CFLAGS) 

greedy: greedy.c
	cc -o $@ $^ $(CFLAGS) 

chart: chart.c
	cc -o $@ $^ $(CFLAGS) 

credit: credit.c
	cc -o $@ $^ $(CFLAGS) 
